// DO NOT EDIT
// This file is automatically generated!
// $ smg.shen rtl/SMG/kseq.smg
//
// https://github.com/sam-falvo/smg

module kseq(
	input 	cfg,
	input 	t5,
	input 	t4,
	input 	t3,
	input 	t2,
	input 	t1,
	input 	wb_we_i,
	input 	t0,
	input 	wb_cyc_i,
	input 	wb_stb_i,
	input 	reset_i,
	output 	clk_en,
	output 	adr_bcrcfg,
	output 	ram_cre_o,
	output 	cfg_o,
	output 	ram_be_valid,
	output 	wb_ack_o,
	output 	dq_dati,
	output 	dato_dq,
	output 	ram_we_o,
	output 	ram_oe_o,
	output 	ram_ce_o,
	output 	ram_adv_o,
	output 	nt5,
	output 	nt4,
	output 	nt3,
	output 	nt2,
	output 	nt1,
	output 	nt0
);
wire R1391 = (|reset_i) ; 
wire R1392 = ~(|reset_i) & ~(|wb_stb_i) & ~(|cfg) ; 
wire R1393 = ~(|reset_i) & ~(|wb_cyc_i) & ~(|cfg) ; 
wire R1394 = ~(|reset_i) & (|cfg) & (|t0) ; 
wire R1395 = ~(|reset_i) & (|cfg) & (|t1) ; 
wire R1396 = ~(|reset_i) & (|cfg) & (|t2) ; 
wire R1397 = ~(|reset_i) & (|cfg) & (|t3) ; 
wire R1398 = ~(|reset_i) & (|cfg) & (|t4) ; 
wire R1399 = ~(|reset_i) & (|cfg) & (|t5) ; 
wire R1400 = ~(|reset_i) & (|wb_stb_i) & (|wb_cyc_i) & ~(|cfg) & ~(|wb_we_i) & (|t0) ; 
wire R1401 = ~(|reset_i) & (|wb_stb_i) & (|wb_cyc_i) & ~(|cfg) & ~(|wb_we_i) & (|t1) ; 
wire R1402 = ~(|reset_i) & (|wb_stb_i) & (|wb_cyc_i) & ~(|cfg) & ~(|wb_we_i) & (|t2) ; 
wire R1403 = ~(|reset_i) & (|wb_stb_i) & (|wb_cyc_i) & ~(|cfg) & ~(|wb_we_i) & (|t3) ; 
wire R1404 = ~(|reset_i) & (|wb_stb_i) & (|wb_cyc_i) & ~(|cfg) & ~(|wb_we_i) & (|t4) ; 
wire R1405 = ~(|reset_i) & (|wb_stb_i) & (|wb_cyc_i) & ~(|cfg) & ~(|wb_we_i) & (|t5) ; 
wire R1406 = ~(|reset_i) & (|wb_stb_i) & (|wb_cyc_i) & ~(|cfg) & (|wb_we_i) & (|t0) ; 
wire R1407 = ~(|reset_i) & (|wb_stb_i) & (|wb_cyc_i) & ~(|cfg) & (|wb_we_i) & (|t1) ; 
wire R1408 = ~(|reset_i) & (|wb_stb_i) & (|wb_cyc_i) & ~(|cfg) & (|wb_we_i) & (|t2) ; 
wire R1409 = ~(|reset_i) & (|wb_stb_i) & (|wb_cyc_i) & ~(|cfg) & (|wb_we_i) & (|t3) ; 
wire R1410 = ~(|reset_i) & (|wb_stb_i) & (|wb_cyc_i) & ~(|cfg) & (|wb_we_i) & (|t4) ; 
wire R1411 = ~(|reset_i) & (|wb_stb_i) & (|wb_cyc_i) & ~(|cfg) & (|wb_we_i) & (|t5) ; 
wire  out1412 = R1391 ? 1 : 0 ; 
wire  out1413 = R1391 ? 1 : 0 ; 
wire  out1414 = R1392 ? 1 : 0 ; 
wire  out1415 = R1393 ? 1 : 0 ; 
wire  out1416 = R1394 ? 1 : 0 ; 
wire  out1417 = R1394 ? 1 : 0 ; 
wire  out1418 = R1394 ? 1 : 0 ; 
wire  out1419 = R1394 ? 1 : 0 ; 
wire  out1420 = R1394 ? 1 : 0 ; 
wire  out1421 = R1394 ? 1 : 0 ; 
wire  out1422 = R1394 ? 1 : 0 ; 
wire  out1423 = R1395 ? 1 : 0 ; 
wire  out1424 = R1395 ? 1 : 0 ; 
wire  out1425 = R1395 ? 1 : 0 ; 
wire  out1426 = R1395 ? 1 : 0 ; 
wire  out1427 = R1395 ? 1 : 0 ; 
wire  out1428 = R1396 ? 1 : 0 ; 
wire  out1429 = R1396 ? 1 : 0 ; 
wire  out1430 = R1396 ? 1 : 0 ; 
wire  out1431 = R1396 ? 1 : 0 ; 
wire  out1432 = R1397 ? 1 : 0 ; 
wire  out1433 = R1397 ? 1 : 0 ; 
wire  out1434 = R1397 ? 1 : 0 ; 
wire  out1435 = R1397 ? 1 : 0 ; 
wire  out1436 = R1398 ? 1 : 0 ; 
wire  out1437 = R1398 ? 1 : 0 ; 
wire  out1438 = R1398 ? 1 : 0 ; 
wire  out1439 = R1398 ? 1 : 0 ; 
wire  out1440 = R1399 ? 1 : 0 ; 
wire  out1441 = R1400 ? 1 : 0 ; 
wire  out1442 = R1400 ? 1 : 0 ; 
wire  out1443 = R1400 ? 1 : 0 ; 
wire  out1444 = R1400 ? 1 : 0 ; 
wire  out1445 = R1400 ? 1 : 0 ; 
wire  out1446 = R1401 ? 1 : 0 ; 
wire  out1447 = R1401 ? 1 : 0 ; 
wire  out1448 = R1401 ? 1 : 0 ; 
wire  out1449 = R1402 ? 1 : 0 ; 
wire  out1450 = R1402 ? 1 : 0 ; 
wire  out1451 = R1402 ? 1 : 0 ; 
wire  out1452 = R1403 ? 1 : 0 ; 
wire  out1453 = R1403 ? 1 : 0 ; 
wire  out1454 = R1403 ? 1 : 0 ; 
wire  out1455 = R1404 ? 1 : 0 ; 
wire  out1456 = R1404 ? 1 : 0 ; 
wire  out1457 = R1404 ? 1 : 0 ; 
wire  out1458 = R1404 ? 1 : 0 ; 
wire  out1459 = R1404 ? 1 : 0 ; 
wire  out1460 = R1405 ? 1 : 0 ; 
wire  out1461 = R1405 ? 1 : 0 ; 
wire  out1462 = R1405 ? 1 : 0 ; 
wire  out1463 = R1406 ? 1 : 0 ; 
wire  out1464 = R1406 ? 1 : 0 ; 
wire  out1465 = R1406 ? 1 : 0 ; 
wire  out1466 = R1406 ? 1 : 0 ; 
wire  out1467 = R1406 ? 1 : 0 ; 
wire  out1468 = R1407 ? 1 : 0 ; 
wire  out1469 = R1407 ? 1 : 0 ; 
wire  out1470 = R1407 ? 1 : 0 ; 
wire  out1471 = R1408 ? 1 : 0 ; 
wire  out1472 = R1408 ? 1 : 0 ; 
wire  out1473 = R1408 ? 1 : 0 ; 
wire  out1474 = R1409 ? 1 : 0 ; 
wire  out1475 = R1409 ? 1 : 0 ; 
wire  out1476 = R1409 ? 1 : 0 ; 
wire  out1477 = R1409 ? 1 : 0 ; 
wire  out1478 = R1409 ? 1 : 0 ; 
wire  out1479 = R1410 ? 1 : 0 ; 
wire  out1480 = R1410 ? 1 : 0 ; 
wire  out1481 = R1410 ? 1 : 0 ; 
wire  out1482 = R1410 ? 1 : 0 ; 
wire  out1483 = R1410 ? 1 : 0 ; 
wire  out1484 = R1411 ? 1 : 0 ; 
wire  out1485 = R1411 ? 1 : 0 ; 
wire  out1486 = R1411 ? 1 : 0 ; 
assign cfg_o = out1439|out1435|out1431|out1427|out1422|out1413;
assign clk_en = out1486|out1483|out1478|out1473|out1470|out1467|out1462|out1459|out1454|out1451|out1448|out1445;
assign ram_ce_o = out1480|out1475|out1472|out1469|out1464|out1456|out1453|out1450|out1447|out1442|out1437|out1433|out1429|out1424|out1417;
assign adr_bcrcfg = out1425|out1420;
assign wb_ack_o = out1485|out1461;
assign dq_dati = out1481|out1476;
assign dato_dq = out1458;
assign ram_oe_o = out1457;
assign ram_cre_o = out1418;
assign ram_adv_o = out1465|out1443|out1419;
assign ram_be_valid = out1482|out1477|out1444;
assign ram_we_o = out1466|out1438|out1434|out1430|out1426|out1421;
assign nt0 = out1484|out1460|out1440|out1415|out1414|out1412;
assign nt1 = out1463|out1441|out1416;
assign nt2 = out1468|out1446|out1423;
assign nt3 = out1471|out1449|out1428;
assign nt4 = out1474|out1452|out1432;
assign nt5 = out1479|out1455|out1436;
endmodule
